HW k8s operator
otus-kuber-2020-04/Shtriga_platform pull request #7
Opened 2020-06-14 12:58 UTC by Shtriga

# Выполнено ДЗ №

 - [X] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 Был создан кастомный ресурс типа для mysql
 И оператор к нему, который сконфигурировал инстанс.

## вывод команды kubectl get jobs
тут у меня возникла странность. статус restore задания не меняется, но данные восстанавливаются, после удлаения вольюма.
 ```sh
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl get jobs
NAME                         COMPLETIONS   DURATION   AGE
backup-mysql-instance-job    1/1           2s         51s
restore-mysql-instance-job   0/1           19m        19m
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ export MYSQLPOD=$(kubectl get pods -l app=mysql-instance -o jsonpath="{.items[*].metadata.name}")
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl exec -it $MYSQLPOD -- mysql -potuspassword -e "select * from test;" otus-database
mysql: [Warning] Using a password on the command line interface can be insecure.
+----+-------------+
| id | name        |
+----+-------------+
|  1 | some data   |
|  2 | some data-2 |
+----+-------------+
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ 
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ 
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ 
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl delete mysqls.otus.homework mysql-instance 
mysql.otus.homework "mysql-instance" deleted
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl get pv
NAME                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS   REASON   AGE
backup-mysql-instance-pv   1Gi        RWO            Retain           Bound    default/backup-mysql-instance-pvc                           20m
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ 
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ 
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl get jobs
NAME                         COMPLETIONS   DURATION   AGE
backup-mysql-instance-job    1/1           2s         27s
restore-mysql-instance-job   0/1           21m        21m
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl apply -f ./cr.yml 
mysql.otus.homework/mysql-instance created
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl get pv
NAME                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS   REASON   AGE
backup-mysql-instance-pv   1Gi        RWO            Retain           Bound    default/backup-mysql-instance-pvc                           21m
mysql-instance-pv          1Gi        RWO            Retain           Bound    default/mysql-instance-pvc                                  22s
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ export MYSQLPOD=$(kubectl get pods -l app=mysql-instance -o jsonpath="{.items[*].metadata.name}")
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl exec -it $MYSQLPOD -- mysql -potuspassword -e "select * from test;" otus-databasemysql: [Warning] Using a password on the command line interface can be insecure.
+----+-------------+
| id | name        |
+----+-------------+
|  1 | some data   |
|  2 | some data-2 |
+----+-------------+
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl get jobs
NAME                         COMPLETIONS   DURATION   AGE
backup-mysql-instance-job    1/1           2s         78s
restore-mysql-instance-job   0/1           22m        22m
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ kubectl logs mysql-operator-5f8d4b579f-gkrsq
[2020-06-14 12:19:51,232] kopf.engines.peering [WARNING ] Default peering object not found, falling back to the standalone mode.
/mysql-operator.py:28: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  json_manifest = yaml.load(yaml_manifest)
[2020-06-14 12:22:21,775] kopf.objects         [INFO    ] [default/mysql-instance] Handler 'mysql_on_create' succeeded.
[2020-06-14 12:22:21,776] kopf.objects         [INFO    ] [default/mysql-instance] All handlers succeeded for creation.
[2020-06-14 12:36:18,899] kopf.objects         [INFO    ] [default/mysql-instance] Handler 'delete_object_make_backup' succeeded.
[2020-06-14 12:36:18,900] kopf.objects         [INFO    ] [default/mysql-instance] All handlers succeeded for deletion.
[2020-06-14 12:38:36,283] kopf.objects         [INFO    ] [default/mysql-instance] Handler 'mysql_on_create' succeeded.
[2020-06-14 12:38:36,284] kopf.objects         [INFO    ] [default/mysql-instance] All handlers succeeded for creation.
[2020-06-14 12:41:09,100] kopf.objects         [INFO    ] [default/mysql-instance] Handler 'delete_object_make_backup' succeeded.
[2020-06-14 12:41:09,101] kopf.objects         [INFO    ] [default/mysql-instance] All handlers succeeded for deletion.
[2020-06-14 12:41:34,111] kopf.objects         [INFO    ] [default/mysql-instance] Handler 'mysql_on_create' succeeded.
[2020-06-14 12:41:34,111] kopf.objects         [INFO    ] [default/mysql-instance] All handlers succeeded for creation.
[2020-06-14 12:43:08,513] kopf.objects         [INFO    ] [default/mysql-instance] Handler 'delete_object_make_backup' succeeded.
[2020-06-14 12:43:08,514] kopf.objects         [INFO    ] [default/mysql-instance] All handlers succeeded for deletion.
[2020-06-14 12:43:38,776] kopf.objects         [INFO    ] [default/mysql-instance] Handler 'mysql_on_create' succeeded.
[2020-06-14 12:43:38,776] kopf.objects         [INFO    ] [default/mysql-instance] All handlers succeeded for creation.
kirsan@msi ~/Documents/OTUS/HW/Shtriga_platform/kubernetes-operators/deploy $ 

```

## PR checklist:
 - [X] Выставлен label с темой домашнего задания

2020-06-14 14:58 UTC, Jasstkn commented
@Shtriga у вас тесты упали
`error: unable to recognize "kubernetes-operators/deploy/crd.yml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"`

2020-06-14 14:58 UTC, Jasstkn requested changes
Добрый вечер. Добейтесь успешного выполнения тестов

2020-06-15 13:30 UTC, Shtriga commented
есть проблемка, восстановление БД видимо не происходит. тест на ней падает. как я могу повлиять на нее?

2020-06-17 05:55 UTC, Jasstkn commented
> есть проблемка, восстановление БД видимо не происходит. тест на ней падает. как я могу повлиять на нее?

Скорее всего никак. Проверила локально - вроде бы все отрабатывает.

2020-06-17 05:55 UTC, Jasstkn approved these changes

2020-06-17 05:55 UTC, merged